pagefilter:
  type: FromFilename

table_extraction:
  - type: FromCSV
    params:
      csv_directory: "data/extractions/extracttable"
  - type: LLamaParse
  - type: UnstructuredAPI
    params:
      hi_res_model_name: "yolox"
  - type: UnstructuredAPI
    params:
      hi_res_model_name: "detectron2_onnx"
  - type: Unstructured
    params:
      hi_res_model_name: "yolox"
      pdf_image_dpi: 400
  - type: Unstructured
    params:
      hi_res_model_name: "detectron2_onnx"
      pdf_image_dpi: 400

# table_cleaning:
