from pages.home import show_home
from pages.publication import show_publication
from pages.company import show_company
from pages.country import showo_country
from pages.sector import show_sector
from pages.faq import show_faq
from pages.contact import show_contact
from pages.methodology import show_methodology
from pages.download import show_downlaod_data
from pages.all_viz import show_all_viz